### ISSUE TITLE
Sukebei.Pantsu plugin has some error

### ISSUE THREAD

**Issue by benx203** [4chenz/pantsu-plugin#1]
Hi!
Line 24:
url = self.url+/api/search/?c='+self.supported_categories[cat]+'&q='+what+'&limit='+str(per_page)+'&page='+str(page)
lost a quote.It should be:
url = self.url+'/api/search/?c='+self.supported_categories[cat]+'&q='+what+'&limit='+str(per_page)+'&page='+str(page)

**Comment by 4chenz** [comment]
Nice, fixed.
Sorry it took forever.
