### ISSUE TITLE
API broken

### ISSUE THREAD

**Issue by 4chenz** [4chenz/pantsu-plugin#2]
Pantsu API returns weird number of results causing the plugin to stop searching since it is dependent on the number of results returned.
Will find a workaround soon.
![1505788328933 1](https://user-images.githubusercontent.com/25059560/30573618-25158800-9cb2-11e7-85aa-5d9374cbfdf6.png)

**Comment by 4chenz** [comment]
Tried searching until it returns zero torrents, it returns dupes.
All of the results are returned but I'm not sure this is a good solution.

**Comment by Pireo** [comment]
Results can't redirect to the web page.

**Comment by 4chenz** [comment]
Plugin now uses "totalRecordCount" from the json to decide how many pages to get instead of relying on the number of results that are supposed to be returned.
ez

**Comment by 4chenz** [comment]
What exactly do you mean by "Results can't redirect to the web page"?
Are you talking about it grabbing magnet links instead of torrent files?
pantsu.cat does not currently have all of the torrent files.
I don't think the intended behavior of any qbit plugin is to redirect to a web page?

**Comment by 4chenz** [comment]
Oh, I see. I looked over the documentation again. I didn't see "desc_link" before.
Added. You should be able to copy the link or open it now.
I'm not sure what it has to do with this issue, though.
Please make posts relevant to the issue or create new issues in the future.
